ALMACEN = "ALMACEN"
VENDIDO = "VENDIDO"
SALIDA = "SALIDA"
GARANTIA = "GARANTIA"

ESTADO_EQUIPO_CHOICES = (
    (ALMACEN, ALMACEN),
    (VENDIDO, VENDIDO),
    (SALIDA, SALIDA),
    (GARANTIA, GARANTIA),
)
